config/routes.rb
Rails.application.routes.draw do

   root 'pages#index'

  resources :videos

end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		@videos = Video.all.order(:title)
	end
end

app/controllers/videos_controller.rb
require 'open-uri'

class VideosController < ApplicationController

  http_basic_authenticate_with name: "modifier", password: "SharingVide0s", except: :show
	
  def index
    	@videos = Video.all.order(:title)
  end
	def new
		@video = Video.new
	end
	def edit
  		@video = Video.find(params[:id])
	end
	def create
		@video = Video.new(video_params)
 		
 		if @video.save
  			redirect_to @video
  		else
    		render 'new'
  		end
	end
	def update
  		@video = Video.find(params[:id])

  		if @video.update(video_params)
    		redirect_to @video
  		else
    		render 'edit'
  		end
	end
	def show
		@video = Video.find(params[:id])
		@pageTitle = @video.title
	end
	def destroy
    	@video = Video.find(params[:id])
    	@video.destroy
 
    	redirect_to videos_path
  end
	private
  		def video_params
    		params.require(:video).permit(:title, :vimeoid, :description, :video_type, :subjects)
  		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/common/_branding.html.haml
.container.mn-brand
   .row
      .col-sm-7
         %ul.mynav#lg-nav
            %li
               %a{:href => "#videos"} Videos
            %li
               %a.about{:href => "#about"} About
            %li
               %a{:href => "#partners"} Partners
            %li
               %a{:href => "#contact"} Contact
         .full-title
            %h1
               Sharing
               %span Spirit
            %p.tagline
               A video archive of first nation's
               %em stories
               \&amp;
               %em knowledge
      .col-sm-5
         =image_tag "logo.png", :alt => "Sharing Spirit Logo", :class => "img-responsive logo hidden-xs"

app/views/common/_form.html.haml
= form_for @video, {:html => {:class => "add-form"}} do |f|
  %ul
    %li
      = f.label :title
      = f.text_field :title, :required => true
    %li
      = f.label "Vimeo Id"
      = f.text_field :vimeoid, :required => true
    %li
      = f.label :type
      = f.text_field :video_type, :required => true
    %li
      = f.label :subject
      = f.text_field :subjects, :required => true
    %li
      = f.label :description
      = f.text_area :description, :as => :text, :required => false, :input_html => {:rows => 10}  
    .form-actions
      = f.submit :class =>'btn btn-primary'

app/views/common/_smbranding.html.haml
.container-wrap.bg
   .container
      .row.sm-brand
         .col-xs-1
            =link_to image_tag("logo-sm.png", :alt => "Sharing Spirit Logo", :class => "sm-logo", :"data-no-turbolink"=>true), root_path 
         .col-xs-5
            %a{:href => "/", :"data-no-turbolink"=>true}
               %h1.sm Sharing <span>Spirit</span>
         .col-xs-6
            %ul.mynav#sm-nav
               %li
                  = link_to "Home", root_path, :"data-no-turbolink"=>true
               %li
                  %a{:href => "/#videos"} Videos
               %li
                  %a{:href => "/#about"} About
               %li
                  %a{:href => "/#partners"} Partners
               %li
                  %a{:href => "/#contact", :class => "last"} Contact
    
      

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "X-UA-Compatible"}/
    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }
    %title SharingSpirit
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Playfair+Display:400,700,400italic,700italic|PT+Sans+Narrow', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
   
    = yield

app/views/pages/index.html.haml
.container-wrap.mv-brand
   .container
      .col-xs-1
         =link_to image_tag("logo-sm.png", :alt => "Sharing Spirit Logo", :class => "sm-logo"), root_path 
      .col-xs-5
         %a{:href => "#top"}
            %h1.sm Sharing <span>Spirit</span>
      .col-xs-6
         %ul.mynav#sm-nav
            %li
               %a{:href => "#top"} TOP
            %li
               %a{:href => "#videos"} Videos
            %li
               %a.about{:href => "#about"} About
            %li
               %a{:href => "#partners"} Partners
            %li
               %a{:href => "#contact"} Contact
= render "common/branding"
.container-wrap.pane
   .container
      .row
         %a{:class => "anchor", :id => "videos"}
         #filters
            %a{"data-filter" => "*"}
               show all
            %a{"data-filter" => ".interview"}
               interviews
            %a{"data-filter" => ".doc"}
               mini-documentaries
      .row
         %div#video-container
            - @videos.each do |video|
               - vid = VideoInfo.new("https://vimeo.com/"+video.vimeoid)
               .video-card{"class" =>"#{video.video_type}"}
                  - vthumb = vid.thumbnail_large
                  - vthumb[0..3] = "https"
                  = image_tag vthumb, :alt => video.title+" thumb"
                  = link_to video_path(video) do
                     %span{"class" =>"#{video.video_type}"}
                        = vid.title
.container-wrap.pane2
   .container
      .row
         %a{:class => "anchor", :id => "about"}
         .col-md-6.about-wrap.hidden-xs
            .med-wheel
               = image_tag "circle.png", :alt => "Medicine Wheel", :class => "img-responsive"
               %p
                  The teachings of the Medicine Wheel informed much of this project. 
         .about-text.col-md-6
            %h2 About Sharing Spirit
            %p 
               Sharing Spirit is an oral history and storytelling project that works with Aboriginal peoples of all ages to share knowledge and tell stories through digital filmmaking. The project was started by Edmonton-based filmmaker Jason Gondziola and Cree Elder Francis Whiskeyjack. Through this project, youth interviewed Elders, Knowledge Keepers and artists on a number of subjects and created short documentary films from some of these interviews.
            %p 
               The project ran principally at amiskwaciy Academy with additional interviews at Prince Charles School, O’Leary Catholic High School, St. Joseph High School and St. Francis Xavier Catholic High School in Edmonton, Alberta, as well as Peace Regional Outreach Campus in Peace River, Alberta.
            %p 
               In this project we connect Aboriginal peoples from different generations, nations and communities to share their knowledge, wisdom and insight. These conversations are to encourage young people to learn not only from their elders, but from each other as well. Our hope is that, through this website, you will be able to learn from them, too.
.container-wrap.pane3
   .container
      .row.visible-xs
         %ul
            %li
               =link_to "Aboriginal Affairs and Northern Development", "https://www.aadnc-aandc.gc.ca/eng/1100100010002/1100100010021" 
            %li
               =link_to "City of Edmonton", "http://www.edmonton.ca/" 
            %li
               =link_to "Edmonton Arts Council", "http://www.edmontonarts.ca/" 
            %li
               =link_to "Wellness Fund", "http://www.wellnessfund.ualberta.ca/" 
            %li
               =link_to "Alberta Historical Resources Foundation Logo", "http://culture.alberta.ca/heritage-and-museums/foundations/alberta-historical-resources-foundation/" 
            %li   
               %h3.logistical Logistical and in-kind support
            %li
               =link_to "Alberta Government", "http://alberta.ca/" 
            %li
               =link_to "Royal Alberta Museums Logo", "http://www.royalalbertamuseum.ca/" 
      .row.hidden-xs
         %a{:class => "anchor", :id => "partners"}
         .col-md-2.partner-wrap
            .partners-text
               %p This project would not have been possible without the generous support of these partners.
         .partners-images.col-md-10
            %h3.financial Financial Support
            =link_to image_tag("aandc.jpg", :alt => "AANDC Logo", :id => "aandc-logo", :class => "partners-logo"), "https://www.aadnc-aandc.gc.ca/eng/1100100010002/1100100010021" 
            =link_to image_tag("citylogo.jpg", :alt => "City of Edmonton Logo", :id => "city-logo", :class => "partners-logo"), "http://www.edmonton.ca/" 
            =link_to image_tag("eac.jpg", :alt => "Edmonton Arts Council Logo", :id => "eac-logo", :class => "partners-logo"), "http://www.edmontonarts.ca/" 
            =link_to image_tag("wf.jpg", :alt => "Wellness Fund Logo", :id => "wf-logo", :class => "partners-logo"), "http://www.wellnessfund.ualberta.ca/" 
            =link_to image_tag("ahrf.jpg", :alt => "Alberta Historical Resources Foundation Logo", :id => "ahrf-logo", :class => "partners-logo"), "http://culture.alberta.ca/heritage-and-museums/foundations/alberta-historical-resources-foundation/" 
            %h3.logistical Logistical and in-kind support
            =link_to image_tag("abgov.jpg", :alt => "Alberta Government Logo", :id => "abgov-logo", :class => "partners-logo"), "http://alberta.ca/" 
            =link_to image_tag("ram.jpg", :alt => "Royal Alberta Museums Logo", :id => "ram-logo", :class => "partners-logo"), "http://www.royalalbertamuseum.ca/" 
.container-wrap.pane4
   .container
      .row
         %a{:class => "anchor", :id => "contact"}
         %h2.contact-head Contact
         %p.contact.col-md-7 
            For further information about this project please contact <br/>
            %a{:href =>"mailto:jason@mtset.com"} 
               Jason Gondziola at mtset Productions 
            in Edmonton, Alberta
         .col-md-5
            =link_to image_tag("mtset-logo-small.jpg", :alt => "mtset Logo", :class => "sm-logo"), "http://mtset.com/"

app/views/videos/edit.html.haml
.container
  %h2 Edit Video
  = render "common/form"

app/views/videos/index.html.haml
.container-wrap
	.container
		%h2 Videos
		%ul
			%li
				= link_to "Add New Video", new_video_path	
		%ol.video-update-list
			- @videos.each do |video|
				%li
					= link_to video.title, video_path(video), :class => "video-title"
					= link_to 'Edit', edit_video_path(video), :class => "video-modify"
					= link_to 'Delete', video_path(video), :class => "video-modify", method: :delete, data: { confirm: 'Are you sure you want to delete this video?' }

app/views/videos/new.html.haml
.container
  %h2 Add Video
  = form_for :video, :html => {:class => 'add-form'}, url: videos_path do |f|
    %ul
      %li
        = f.label :title
        = f.text_field :title, :required => true
      %li
        = f.label "Vimeo Id"
        = f.text_field :vimeoid, :required => true
      %li
        = f.label :type
        = f.text_field :type, :required => true
      %li
        = f.label :subject
        = f.text_field :subject, :required => true
      %li
        = f.label :description
        = f.text_area :description, :as => :text, :required => false, :input_html => {:rows => 10}  
      .form-actions
        = f.submit :class =>'btn btn-primary'

app/views/videos/show.html.haml
= render "common/smbranding"
.container.video-container
	- vid = VideoInfo.new("https://vimeo.com/"+@video.vimeoid)
	%h2.video-title
		= vid.title
	.video-wrapper.col-md-12
		%iframe{:src => "https://player.vimeo.com/video/"+@video.vimeoid+"?title=0&amp;byline=0&amp;portrait=0", :allowfullscreen => "true"}
	.video-info.col-md-12
		%p
			= vid.description.html_safe
			=link_to "Share on Facebook", "https://www.facebook.com/sharer/sharer.php?u=https://vimeo.com/"+@video.vimeoid



	